<?php
/**
 * @file
 *
 * Helper module to generate hvac codes from urls automatically.
 */

/**
 * Implements hook_menu().
 */
/*function hvac_menu() {
  $items['admin/config/media/hvac'] = array(
    'title' => 'hvac Settings',
    'description' => 'Configure hvac settings.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('hvac_admin_settings'),
    'access arguments' => array('administer site configuration'),
    'file' => 'hvac.admin.inc',
  );
  return $items;
}*/

/**
 * Implements hook_node_view().
 */
function hvac_node_view($node, $view_mode, $langcode) {
  switch ($view_mode) {
    case 'full':
      switch ($node->type) {
        case 'product':
          break;

        default:
          break;
      }
      break;

    default:
      break;
  }
}

